# cd.prod.yml
name: CI/CD Pipeline

on:
  push:
    branches: [main] # on Push
  pull_request:
    branches: [main] # on PR

env:
  GHCR_REGISTRY: ghcr.io
  IMAGE_BASENAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}
  # Secrets:
  GHCR_PAT_OR_TOKEN: ${{ secrets.PROD_GHCR_PAT_OR_TOKEN }}
  SERVER_USER: ${{ secrets.PROD_SERVER_USER }}
  SERVER_HOST: ${{ secrets.PROD_SERVER_HOST }}
  SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
  ENV_FILE_CONTENT: ${{ secrets.PROD_ENV_FILE }}
  # Commands:
  SSH_CMD: ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_SERVER_USER }}@${{ secrets.PROD_SERVER_HOST }}
  SCP_CMD: scp -o StrictHostKeyChecking=no
  # paths:
  ENV_FILE: .env.production
  DEPLOY_DIR: ./deployment/rust-actix-web_cd
  FRONTEND_PATH: ./frontend
  NGINX_FILE_PATH: ./frontend/nginx.conf
  BACKEND_PATH: ./backend
  DOCKER_COMPOSE_FILE: ./docker-compose.prod.yml
  DEPLOY_SCRIPT: ./deployment/scripts/deploy.sh
  DOCKER_LOGIN_SCRIPT: ./deployment/scripts/docker-login.sh

jobs:
  # job for linting and testing (not implemented yet)
  lint-test:
    name: Lint & Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  build-push:
    name: Build & Push Docker Images
    needs: lint-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GHCR_PAT_OR_TOKEN }}

      - name: Lowercase Image Base Name
        id: lowercaser
        run: echo "image_base=$(echo ${{ env.IMAGE_BASENAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Define Image Tags
        id: image_tags
        run: |
          TAG_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "tag_sha=${TAG_SHA}" >> $GITHUB_OUTPUT
          echo "tag_latest=latest" >> $GITHUB_OUTPUT
          echo "backend_image=${{ steps.lowercaser.outputs.image_base }}/backend" >> $GITHUB_OUTPUT
          echo "frontend_image=${{ steps.lowercaser.outputs.image_base }}/frontend" >> $GITHUB_OUTPUT

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BACKEND_PATH }}
          file: ${{ env.BACKEND_PATH }}/Dockerfile
          push: true
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ steps.image_tags.outputs.backend_image }}:${{ steps.image_tags.outputs.tag_latest }}
            ${{ env.GHCR_REGISTRY }}/${{ steps.image_tags.outputs.backend_image }}:${{ steps.image_tags.outputs.tag_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.FRONTEND_PATH }}
          file: ${{ env.FRONTEND_PATH }}/Dockerfile
          push: true
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ steps.image_tags.outputs.frontend_image }}:${{ steps.image_tags.outputs.tag_latest }}
            ${{ env.GHCR_REGISTRY }}/${{ steps.image_tags.outputs.frontend_image }}:${{ steps.image_tags.outputs.tag_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Server
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Define Image Tags for Deployment
        id: image_tags
        run: |
          TAG_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          IMAGE_BASE_LOWER=$(echo "${{ env.IMAGE_BASENAME }}" | tr '[:upper:]' '[:lower:]')
          echo "backend_image=${{ env.GHCR_REGISTRY }}/${IMAGE_BASE_LOWER}/backend:${TAG_SHA}" >> $GITHUB_OUTPUT
          echo "frontend_image=${{ env.GHCR_REGISTRY }}/${IMAGE_BASE_LOWER}/frontend:${TAG_SHA}" >> $GITHUB_OUTPUT

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: mkdir -p ~/.ssh && ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Create .env file
        run: |
          echo "${{ env.ENV_FILE_CONTENT }}" > ${{ env.ENV_FILE }}

      - name: Transfer files to server
        run: |
          SERVER_DEST="${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.DEPLOY_DIR }}"

          # mkdir
          ${{ env.SSH_CMD }} "mkdir -p ${{ env.DEPLOY_DIR }}" 

          # scp
          ${{ env.SCP_CMD }} \
            ${{ env.DOCKER_COMPOSE_FILE }} \
            ${{ env.ENV_FILE }} \
            ${{ env.NGINX_FILE_PATH }} \
            ${{ env.DEPLOY_SCRIPT }} \
            ${{ env.DOCKER_LOGIN_SCRIPT }} \
            ${SERVER_DEST}

        # ------------------------------------------

      - name: Execute Deployment on Server
        run: |
          DEPLOY_DIR="${{ env.DEPLOY_DIR }}"
          ENV_FILE="${{ env.ENV_FILE }}"
          DOCKER_COMPOSE_FILE="${{ env.DOCKER_COMPOSE_FILE }}"
          NGINX_FILE_PATH="${{ env.NGINX_FILE_PATH }}"
          DEPLOY_SCRIPT="${{ env.DEPLOY_SCRIPT }}"
          DOCKER_LOGIN_SCRIPT="${{ env.DOCKER_LOGIN_SCRIPT }}"
          GHCR_PAT_OR_TOKEN="${{ env.GHCR_PAT_OR_TOKEN }}"
          GHCR_REGISTRY="${{ env.GHCR_REGISTRY }}"
          GITHUB_ACTOR="${{ github.actor }}"

          ${{ env.SSH_CMD }} << EOF
            cd ~/${DEPLOY_DIR}
            mv ${ENV_FILE} .env
            mv ${DOCKER_COMPOSE_FILE} docker-compose.yml
            mv ${NGINX_FILE_PATH} nginx.conf

                # ------------------------------       
                # ----- files in server --------
                # ~/deployment/rust-actix-web_cd/
                  # ├── .env
                  # ├── docker-compose.yml
                  # ├── nginx.conf
                  # ├── deploy.sh
                  # └── docker-login.sh

            # --- Login, Deploy, Logout ---
            chmod +x ./docker-login.sh
            ./docker-login.sh "${GHCR_PAT_OR_TOKEN}" "${GHCR_REGISTRY}" "${GITHUB_ACTOR}"
            
            echo "Running deployment script (deploy.sh)..."
            chmod +x ./deploy.sh
            ./deploy.sh

            echo "Logging out from GHCR..."
            docker logout ${GHCR_REGISTRY}
          EOF
